name: Conditions
on: push

jobs:
  mes-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Etape 1
        run: echo "Test OK"

      - name: Etape 2
        if : github.ref == 'refs/heads/main'
        run: echo "Déploiement en cours..."


